version: '2.1'

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8079:8080
    depends_on:
      - broker
      - broker2
      - broker3
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092,broker2:9093,broker3:9094
#      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
#      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
#      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
#      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
#      KAFKA_CLUSTERS_1_NAME: secondLocal
#      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: broker2:29092
#      KAFKA_CLUSTERS_2_NAME: thridLocal
#      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: broker3:29092
#      KAFKA_CLUSTERS_1_METRICS_PORT: 9998
#      KAFKA_CLUSTERS_1_SCHEMAREGISTRY: http://schemaregistry1:8085
#      DYNAMIC_CONFIG_ENABLED: 'true'

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=broker:9092,broker2:9093,broker3:9094
      - ZOOKEEPER=zookeeper:2181
  broker2:
    image: confluentinc/cp-kafka:latest
    container_name: broker2
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker2:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=broker:9092,broker2:9093,broker3:9094
      - ZOOKEEPER=zookeeper:2181
  broker3:
    image: confluentinc/cp-kafka:latest
    container_name: broker3
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker3:9094
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9094
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=3
      - BOOTSTRAP_SERVERS=broker:9092,broker2:9093,broker3:9094
      - ZOOKEEPER=zookeeper:2181