version: '3.8'
name: mall
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /d/shared/mall/mysql/data:/var/lib/mysql #数据文件目录挂载
      - /d/shared/mall/mysql/conf:/etc/mysql #配置文件目录挂载
      - /d/shared/mall/mysql/log:/var/log/mysql #日志文件目录挂载
  redis:
    image: redis
    container_name: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - /d/shared/mall/redis/data:/data #数据文件目录挂载
    ports:
      - 6379:6379
#  nginx:
#    image: nginx:1.22
#    container_name: nginx
#    volumes:
#      - /d/shared/mall/nginx/conf:/etc/nginx #配置文件目录挂载
#      - /d/shared/mall/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
#      - /d/shared/mall/nginx/logs:/var/log/nginx #日志文件目录挂载
#    ports:
#      - 80:80
  rabbitmq:
    image: rabbitmq:3.12.6-management-alpine
    container_name: rabbitmq
    restart: always
    volumes:
      - /d/shared/mall/rabbitmq/data:/var/lib/rabbitmq #数据文件目录挂载
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: elasticsearch
    restart: always
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置es使用的jvm内存大小
    volumes:
      - /d/shared/mall/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件目录挂载
      - /d/shared/mall/elasticsearch/data:/usr/share/elasticsearch/data #数据文件目录挂载
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.17.13
    container_name: logstash
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /d/shared/mall/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.17.13
    container_name: kibana
    restart: always
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    volumes:
      - /d/shared/mall/mongo/db:/data/db #数据文件目录挂载
    ports:
      - 27017:27017
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001" #指定数据目录及console运行端口启动
    volumes:
      - /d/shared/mall/minio/data:/data #数据目录挂载
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - 9000:9000
      - 9001:9001
