version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.13
    environment:
      - discovery.type=single-node 
    ports:
      - "9200:9200"
      - "9300:9300"
  # logstash:
  #   image: logstash:7.17.13
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "5043:5043"
  #     - "5044:5044"
  kibana:
    image: kibana:7.17.13
    depends_on: 
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      # ELASTICSEARCH_USER: admin
      # ELASTICSEARCH_PASSWORD: admin
    ports:
      - "5601:5601"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: http://elasticsearch:9200
      # ES_USERNAME: admin
      # ES_PASSWORD: admin